export enum UserRole {
  USER = 'USER',
  SUPPORT_AGENT = 'SUPPORT_AGENT',
  ADMIN = 'ADMIN',
  SALES = 'SALES'
}

export enum TicketStatus {
  OPEN = 'OPEN',
  IN_PROGRESS = 'IN_PROGRESS',
  ESCALATED = 'ESCALATED',
  RESOLVED = 'RESOLVED',
  CLOSED = 'CLOSED'
}

export enum TicketEventType {
  TICKET_CREATED = 'TICKET_CREATED',
  TICKET_ASSIGNED = 'TICKET_ASSIGNED',
  STATUS_CHANGED = 'STATUS_CHANGED',
  AGENT_REPLY = 'AGENT_REPLY',
  USER_REPLY = 'USER_REPLY',
  INTERNAL_NOTE = 'INTERNAL_NOTE',
  ADMIN_REPLY = 'ADMIN_REPLY',
  SYSTEM_MESSAGE = 'SYSTEM_MESSAGE',
  OUTAGE_DETAILS_CHANGED = 'OUTAGE_DETAILS_CHANGED',
  TICKET_RCA_UPDATED = 'TICKET_RCA_UPDATED',
  REPLY_TOGGLED = 'REPLY_TOGGLED'
}
