export const ErrorCodes = {
  // Authentication & Authorization
  NO_TOKEN: 'NO_TOKEN',
  INVALID_TOKEN: 'INVALID_TOKEN',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  NO_REFRESH_TOKEN: 'NO_REFRESH_TOKEN',
  REFRESH_EXPIRED: 'REFRESH_EXPIRED',
  REFRESH_REVOKED: 'REFRESH_REVOKED',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  REGISTRATION_DISABLED: 'REGISTRATION_DISABLED',

  // Registration & Users
  EMAIL_EXISTS: 'EMAIL_EXISTS',
  INVALID_ROLE: 'INVALID_ROLE',
  CUSTOMER_NOT_FOUND: 'CUSTOMER_NOT_FOUND',
  EMPLOYEE_NOT_FOUND: 'EMPLOYEE_NOT_FOUND',

  // Password Reset
  INVALID_OTP: 'INVALID_OTP',
  OTP_EXPIRED: 'OTP_EXPIRED',
  RATE_LIMIT: 'RATE_LIMIT',

  // Tickets & Workflow
  TICKET_NOT_FOUND: 'TICKET_NOT_FOUND',
  ACTOR_NOT_FOUND: 'ACTOR_NOT_FOUND',
  REQUESTER_NOT_FOUND: 'REQUESTER_NOT_FOUND',
  TICKET_NOT_ASSIGNED: 'TICKET_NOT_ASSIGNED',
  TICKET_CLOSED: 'TICKET_CLOSED',
  TICKET_LOCKED: 'TICKET_LOCKED',
  REOPEN_EXPIRED: 'REOPEN_EXPIRED',
  INVALID_TRANSITION: 'INVALID_TRANSITION',
  RCA_REQUIRED: 'RCA_REQUIRED',
  INVALID_AGENT: 'INVALID_AGENT',
  INVALID_STATUS: 'INVALID_STATUS',
  INVALID_RATING: 'INVALID_RATING',
  INVALID_TICKET_STATE: 'INVALID_TICKET_STATE',

  // System
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  BAD_REQUEST: 'BAD_REQUEST',
  DUPLICATE_KEY: 'DUPLICATE_KEY',
  FOREIGN_KEY_VIOLATION: 'FOREIGN_KEY_VIOLATION',
  NOT_NULL_VIOLATION: 'NOT_NULL_VIOLATION',
} as const;

export type ErrorCode = keyof typeof ErrorCodes;
